load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "json11",
    srcs = ["json11.cpp"],
    hdrs = ["json11.hpp"],
)